Mayúsculas y más...
mindustryes/Mindustry pull request #2
Opened 2022-11-17 10:23 UTC by Angel-24

Núcleo ahora se escribe con minúscula, considerado una palabra cualquiera. También me he encontrado algunas descripciones de unidades de Erekir sin traducir.

2022-11-17 14:51 UTC, ImUrX requested changes

2022-11-20 17:02 UTC, merged

2022-11-22 17:08 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +command = Ordenar
vale

2022-11-22 17:10 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +command.move = Mover
Me quedo con "moverse", porque tanto "mover" como "trasladar" se podrían entender como transportar objetos o similar.

2022-11-22 17:11 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +unit.locus.description = Alterna los proyectiles que dispara a objetivos enemigos.
de acuerdo

2022-11-22 17:12 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +unit.conquer.description = Dispara grandes ráfagas perforantes a los objetivos enemigos.
Un poco innecesario, pero vale

2022-11-22 17:25 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +setting.commandmodehold.name = Mantener para Modo Comando
No. Cuando esta opción está activada (lo está por defecto), el jugador debe mantener el L-Shift para usar el Modo Comando. Si se desactiva, con solo pulsar L-Shift activará el Modo Comando hasta volver a pulsarlo. [En el bundle original es "Hold For Command Mode"].

2022-11-22 17:41 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +unit.vanquish.description = Dispara grandes balas divisibles que perforan a los objetivos enemigos.
Creo que "divisibles" es lo más correcto. Cuando un proyectil se fragmenta, se entiende que lo hace de forma aleatoria e impredecible, similar a los proyectiles de una escopeta, por ejemplo. Por otro lado, cuando un proyectil se divide, entendemos que lo hace de forma "más ordenada" o "predecible". Por ejemplo, los proyectiles grandes de Vanquish siempre se dividen tras recorrer exactamente la misma distancia en cada disparo (y creo que también se dividen en la misma cantidad de proyectiles siempre).

2022-11-22 17:41 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +unit.vanquish.description = Dispara grandes balas divisibles que perforan a los objetivos enemigos.
Pero si no te gusta, lo dejamos como fragmentables.

2022-11-22 18:33 UTC, RexAliis commented on core/assets/bundles/bundle_es.properties
> +setting.commandmodehold.name = Mantener para Modo Comando
Entonces `mantener para Comandar`?

2022-11-23 09:58 UTC, Angel-24 commented on core/assets/bundles/bundle_es.properties
> +setting.commandmodehold.name = Mantener para Modo Comando
Comandar es una alternativa no muy usada en España, pero creo que se entiende bien. Vale, "Mantener para comandar".